In [1]:
import requests
import json

def fetch_page_as_json(url):
    response = requests.get(url)
    response.raise_for_status()  # lança exceção em caso de erro HTTP
    html_content = response.text
    return {"html": html_content}

if __name__ == "__main__":
    url = (
        "https://www.ana.gov.br/sar0/MedicaoCantareira"
        "?dropDownListReservatorios=29002"
        "&dataInicial=01%2F08%2F2025"
        "&dataFinal=25%2F08%2F2025"
    )
    data = fetch_page_as_json(url)
    # salva em arquivo JSON
    print(data)

{'html': '<!doctype html>\r\n<html class="app no-js" lang="pt-br" dir="ltr">\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>..SAR - Sistema de Acompanhamento de Reservatórios</title>\r\n    <meta http-equiv="X-UA-Compatible" content="IE=9">\r\n    <meta name="description" content="Catalogo de interface utilizado nos sistemas da ANA.">\r\n    <meta name="keywords" content="catalogo de interface, protótipo da interface, interface do usuário">\r\n    <meta name="viewport" content="width=device-width">\r\n    <link rel="shortcut icon" href="/sar0/favicon.ico">\r\n    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n    <link rel="stylesheet" href="/sar0/Content/vendor.css">\r\n    <link rel="stylesheet" href="/sar0/Content/main.css">\r\n    <link href="/sar0/Content/dataPicker/bootstrap-datepicker.css" rel="stylesheet" />\r\n\r\n    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZTfm8zekb0gmMchJkT8T9hSEmJs5aiZ4&sensor=false"></script>\r\n    \r\n    \r\n    \r\n    <script type="text/javascript" src="/sar0/Content/scripts/mapaReservatoriosHome.js"></script>\r\n    <script type="text/javascript" src="/sar0/Content/scripts/mapaReservatoriosNordeste.js"></script>\r\n    <script type="text/javascript" src="/sar0/Content/scripts/functions.js"></script>\r\n    <script src="/sar0/Content/scripts/vendor/modernizr.js"></script>\r\n\r\n    \r\n\r\n    \r\n\r\n    <script type="text/javascript" src="/sar0//www.google.com/jsapi"></script>\r\n    <script type="text/javascript">\r\n        google.load(\'visualization\', \'1\', { packages: [\'corechart\'] });\r\n    </script>\r\n\r\n    \r\n\r\n    \r\n\r\n</head>\r\n<body>\r\n\r\n      \r\n\r\n    <input id="auth" name="auth" type="hidden" value="False" />\r\n\r\n    \r\n\r\n\r\n    <!--[if lt IE 9]>\r\n      <p class="browsehappy">Você está usando um navegador <strong>desatualizado</strong>. Por favor, <a href="https://browsehappy.com/" target="_blank">atualize seu navegador</a> para melhorar a sua experiência.</p>\r\n    <![endif]-->\r\n            <p class="browsehappy">\r\n                Para uma melhor experiência de navegação, é recomendada a utilização do <strong>Google Chrome</strong>, versão 40 ou superior. Por favor, <a href="https://browsehappy.com/"> atualize seu navegador</a>.\r\n            </p>\r\n\r\n\r\n    <div id="barra-brasil" style="background: #7f7f7f; height: 20px; padding: 0 0 0 10px; display: block; min-height: 32px;">\r\n        <ul id="menu-barra-temp" style="list-style: none;">\r\n            <li style="display: inline; float: left; padding-right: 10px; margin-right: 10px; border-right: 1px solid #ededed;"><a href="https://brasil.gov.br" style="font-family: sans, sans-serif; text-decoration: none; color: white;">Portal do Governo Brasileiro</a></li>\r\n            <li><a href="https://epwg.governoeletronico.gov.br/barra/atualize.html" style="font-family: sans, sans-serif; text-decoration: none; color: white;">Atualize sua Barra de Governo</a></li>\r\n        </ul>\r\n    </div>\r\n\r\n    <section class="vbox">\r\n        <header class="bg-primary header header-md navbar navbar-fixed-top-xs box-shadow">\r\n            <div class="navbar-header aside-md bg-white">\r\n                <a class="btn btn-link visible-xs" data-toggle-class="nav-off-screen" data-target="#nav">\r\n                    <i class="fa fa-bars"></i>\r\n                </a>\r\n                <a href="/sar0/Home" class="navbar-brand text-center">\r\n                    <figure class="inline m-r-xs">\r\n                        <img src="/sar0/images/logo.png" alt="ANA">\r\n                    </figure>\r\n                </a>\r\n                <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".user">\r\n                    <i class="fa fa-cog"></i>\r\n                </a>\r\n            </div>\r\n            <ul class="nav navbar-nav hidden-xs">\r\n                <li>\r\n                    <a href="#"><i class="i i-book"></i> SAR - Sistema de Acompanhamento de Reservatórios</a>\r\n                </li>\r\n                <!--li class="dropdown" data-toggle="tooltip" title="Seleção de Perfil">\r\n                <a href="#" class="dropdown-toggle" data-toggle="dropdown">\r\n                    <i class="i i-users3"></i>\r\n                </a>\r\n                <ul class="dropdown-menu">\r\n                    <li class="active">\r\n                        <a href="painel.html">Perfil 1</a>\r\n                    </li>\r\n                    <li>\r\n                        <a href="painel.html">Perfil 2</a>\r\n                    </li>\r\n                    <li>\r\n                        <a href="painel.html">Perfil 2</a>\r\n                    </li>\r\n                </ul>\r\n                </li-->\r\n            </ul>\r\n            \r\n\r\n                <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user user">\r\n\r\n                    <!--li class="hidden-sm">\r\n                    <a href="manual.html"><i class="i i-support"></i> <span class="hidden-sm hidden-md">Manual do Sistema</span></a>\r\n                    </li-->\r\n\r\n                    <li class="hidden-sm hidden-md">\r\n                        <a href="#">v2.2.5</a>\r\n                    </li>\r\n                    <li class="hidden-sm">\r\n                        <ul id="rvfs-controllers" class="list-unstyled list-inline list-accessibility padder-h"></ul>\r\n                    </li>\r\n                    <li>\r\n                        <a href="/sar0/Login/Login" id="loginLink">Logar no Sistema</a>\r\n                    </li>\r\n                </ul>\r\n        </header>\r\n        <section>\r\n            <section class="hbox stretch">\r\n                <aside class="bg-white aside-md hidden-print" id="nav">\r\n                    <section class="vbox">\r\n                        <section class="w-f scrollable">\r\n                            <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="10px" data-railopacity="0.2">\r\n                                <div class="clearfix wrapper dk nav-user hidden-xs">\r\n\r\n                                        <div class="dropdown">\r\n                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">\r\n                                                <figure class="thumb avatar pull-left m-r">\r\n                                                    <img src="/sar0/images/profile/avatar.png" alt="Junqueira" class="dker">\r\n                                                    <i class="on md b-black"></i>\r\n                                                </figure>\r\n                                                <span class="hidden-nav-xs clear">\r\n                                                    <span class="block m-t-xs">\r\n                                                        <strong class="text-lt">\r\n                                                            Visitante\r\n                                                        </strong> <i class="fa fa-caret-down"></i>\r\n                                                    </span>\r\n                                                    <span class="text-muted text-xs block">     </span>\r\n                                                </span>\r\n                                            </a>\r\n                                            <ul class="dropdown-menu animated fadeIn m-t-xs">\r\n                                                <li>\r\n                                                    <a href="/sar0/Login/Login">Logar</a>\r\n                                                </li>\r\n                                            </ul>\r\n                                        </div>\r\n\r\n                                </div>\r\n\r\n                                <nav class="nav-primary hidden-xs">\r\n                                    <div class="text-muted text-sm hidden-nav-xs padder-h m-t-sm m-b-sm">Navegação</div>\r\n                                    <ul class="nav nav-main" data-ride="collapse">\r\n                                        <li>\r\n                                            <a href="#" class="auto">\r\n                                                <span class="pull-right text-muted">\r\n                                                    <i class="i i-circle-sm-o text-inactive"></i>\r\n                                                    <i class="i i-circle-sm text-active"></i>\r\n                                                </span>\r\n                                                <i class="i i-docs icon"></i>\r\n                                                <strong>Nordeste e Semiárido</strong>\r\n                                            </a>\r\n                                            <ul class="nav dk">\r\n                                                <li>\r\n                                                    <a href="/sar0/Nordeste" class="auto">\r\n                                                        <i class="i i-dot"></i>\r\n                                                        <span>Volume Por Estado</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="/sar0/Medicao" class="auto">\r\n                                                        <i class="i i-dot"></i>\r\n                                                        <span>Dados Históricos</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="/sar0/Nordeste/GraficoVolume" class="auto">\r\n                                                        <i class="i i-dot"></i>\r\n                                                        <span>Gráfico Volume</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                            </ul>\r\n                                        </li>\r\n\r\n                                        <li>\r\n                                            <a href="#" class="auto">\r\n                                                <span class="pull-right text-muted">\r\n                                                    <i class="i i-circle-sm-o text-inactive"></i>\r\n                                                    <i class="i i-circle-sm text-active"></i>\r\n                                                </span>\r\n                                                <i class="i i-docs icon"></i>\r\n                                                <strong>SIN</strong>\r\n                                            </a>\r\n                                            <ul class="nav dk">\r\n                                                <li>\r\n                                                    <a href="/sar0/MedicaoSin" class="auto">\r\n                                                        <i class="i i-dot"></i>\r\n                                                        <span>Dados Históricos</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                            </ul>\r\n                                        </li>\r\n\r\n                                        <li>\r\n                                            <a href="#" class="auto">\r\n                                                <span class="pull-right text-muted">\r\n                                                    <i class="i i-circle-sm-o text-inactive"></i>\r\n                                                    <i class="i i-circle-sm text-active"></i>\r\n                                                </span>\r\n                                                <i class="i i-docs icon"></i>\r\n                                                <strong>Sistema Cantareira</strong>\r\n                                            </a>\r\n                                            <ul class="nav dk">\r\n                                                <li class="active">\r\n                                                    <a href="/sar0/MedicaoCantareira" class="auto">\r\n                                                        <i class="i i-dot"></i>\r\n                                                        <span>Dados Históricos</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                            </ul>\r\n                                        </li>\r\n\r\n\r\n                                    </ul>\r\n                                    <div class="line dk hidden-nav-xs"></div>\r\n                                    <div class="text-muted text-xs hidden-nav-xs padder-h m-t-sm m-b-sm">\r\n\r\n                                        <div class="pull-right">\r\n                                            <a href="#" data-toggle="tooltip" data-placement="top" title="Itens mais acessados"><i class="fa fa-question-circle-circle"></i></a>\r\n                                        </div>\r\n                                    </div>\r\n                                    <ul class="nav nav-main" data-ride="collapse">\r\n\r\n                                        <li>\r\n                                            <a href="#" class="auto">\r\n                                                <span class="pull-right text-muted">\r\n                                                    <i class="i i-circle-sm-o text-inactive"></i>\r\n                                                    <i class="i i-circle-sm text-active"></i>\r\n                                                </span>\r\n                                                <i class="i i-world icon"></i>\r\n                                                <strong>Acesso Rápido</strong>\r\n                                            </a>\r\n                                            <ul class="nav dk">\r\n                                                <li>\r\n                                                    <a href="https://www.ana.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-info-dk"></i>\r\n                                                        <span>Portal ANA</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.ons.org.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-success-dk"></i>\r\n                                                        <span>ONS</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.dnocs.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-danger-dk"></i>\r\n                                                        <span>DNOCS</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://portal.cogerh.com.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-warning-dk"></i>\r\n                                                        <span>COGERH</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.aesa.pb.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-dark-dk"></i>\r\n                                                        <span>AESA</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.semarh.rn.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-primary-dk"></i>\r\n                                                        <span>SEMARH</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.apac.pe.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-info-dk"></i>\r\n                                                        <span>Apac</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.cerb.ba.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-success-dk"></i>\r\n                                                        <span>Cerb</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.inema.ba.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-danger-dk"></i>\r\n                                                        <span>Inema</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.codevasf.gov.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-warning-dk"></i>\r\n                                                        <span>CODEVASF</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                                <li>\r\n                                                    <a href="https://www.compesa.com.br/" target="alt">\r\n                                                        <i class="i i-circle-sm text-dark-dk"></i>\r\n                                                        <span>COMPESA</span>\r\n                                                    </a>\r\n                                                </li>\r\n                                            </ul>\r\n\r\n                                    </ul>\r\n                                    </li>\r\n                                    </ul>\r\n                                </nav>\r\n                            </div>\r\n                        </section>\r\n                        <footer class="footer hidden-xs no-padder text-center-nav-xs">\r\n                            <a href="javascript:document.getElementById(\'logoutForm\').submit()" class=

In [7]:
print(data['html'].split('<table')[1].split('<tr'))

[' class="table table-striped table-bordered table-hover">\r\n\r\n                                <thead>\r\n                                    ', '>\r\n                                        <th class="text-center" data-sort="coluna_1">C&#243;digo do Reservat&#243;rio</th>\r\n                                        <th class="text-center" data-sort="coluna_2">Reservat&#243;rio</th>\r\n                                        <th class="text-center" data-sort="coluna_3">Cota (m)</th>\r\n                                        <th class="text-center" data-sort="coluna_4">Volume &#218;til (hm&#179;)</th>\r\n                                        <th class="text-center" data-sort="coluna_5">Volume &#218;til (%)</th>\r\n                                        <th class="text-center" data-sort="coluna_6">Aflu&#234;ncia (m&#179;/s)</th>\r\n                                        <th class="text-center" data-sort="coluna_7">Deflu&#234;ncia (m&#179;/s)</th>\r\n                                        <th class="text-center" data-sort="coluna_8">Data da Medi&#231;&#227;o</th>\r\n\r\n\r\n                                    </tr>\r\n                                </thead>\r\n                                <tbody class="list">\r\n\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,56</td>\r\n                                            <td class="text-center coluna_4">28,47</td>\r\n                                            <td class="text-center coluna_5">40,87</td>\r\n                                            <td class="text-center coluna_6">0,92</td>\r\n                                            <td class="text-center coluna_7">4,50</td>\r\n                                            <td class="text-center coluna_8">01/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,58</td>\r\n                                            <td class="text-center coluna_4">28,60</td>\r\n                                            <td class="text-center coluna_5">41,06</td>\r\n                                            <td class="text-center coluna_6">1,75</td>\r\n                                            <td class="text-center coluna_7">4,50</td>\r\n                                            <td class="text-center coluna_8">02/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,58</td>\r\n                                            <td class="text-center coluna_4">28,60</td>\r\n                                            <td class="text-center coluna_5">41,06</td>\r\n                                            <td class="text-center coluna_6">0,23</td>\r\n                                            <td class="text-center coluna_7">4,50</td>\r\n                                            <td class="text-center coluna_8">03/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,58</td>\r\n                                            <td class="text-center coluna_4">28,60</td>\r\n                                            <td class="text-center coluna_5">41,06</td>\r\n                                            <td class="text-center coluna_6">0,33</td>\r\n                                            <td class="text-center coluna_7">4,50</td>\r\n                                            <td class="text-center coluna_8">04/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,57</td>\r\n                                            <td class="text-center coluna_4">28,53</td>\r\n                                            <td class="text-center coluna_5">40,97</td>\r\n                                            <td class="text-center coluna_6">0,14</td>\r\n                                            <td class="text-center coluna_7">4,50</td>\r\n                                            <td class="text-center coluna_8">05/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,55</td>\r\n                                            <td class="text-center coluna_4">28,40</td>\r\n                                            <td class="text-center coluna_5">40,77</td>\r\n                                            <td class="text-center coluna_6">0,29</td>\r\n                                            <td class="text-center coluna_7">4,54</td>\r\n                                            <td class="text-center coluna_8">06/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,59</td>\r\n                                            <td class="text-center coluna_4">28,66</td>\r\n                                            <td class="text-center coluna_5">41,15</td>\r\n                                            <td class="text-center coluna_6">0,74</td>\r\n                                            <td class="text-center coluna_7">5,00</td>\r\n                                            <td class="text-center coluna_8">07/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,61</td>\r\n                                            <td class="text-center coluna_4">28,82</td>\r\n                                            <td class="text-center coluna_5">41,38</td>\r\n                                            <td class="text-center coluna_6">0,14</td>\r\n                                            <td class="text-center coluna_7">5,00</td>\r\n                                            <td class="text-center coluna_8">08/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,62</td>\r\n                                            <td class="text-center coluna_4">28,87</td>\r\n                                            <td class="text-center coluna_5">41,45</td>\r\n                                            <td class="text-center coluna_6">0,13</td>\r\n                                            <td class="text-center coluna_7">5,04</td>\r\n                                            <td class="text-center coluna_8">09/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,62</td>\r\n                                            <td class="text-center coluna_4">28,87</td>\r\n                                            <td class="text-center coluna_5">41,45</td>\r\n                                            <td class="text-center coluna_6">0,14</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">10/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,62</td>\r\n                                            <td class="text-center coluna_4">28,87</td>\r\n                                            <td class="text-center coluna_5">41,45</td>\r\n                                            <td class="text-center coluna_6">0,50</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">11/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,65</td>\r\n                                            <td class="text-center coluna_4">29,07</td>\r\n                                            <td class="text-center coluna_5">41,74</td>\r\n                                            <td class="text-center coluna_6">0,28</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">12/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,63</td>\r\n                                            <td class="text-center coluna_4">28,94</td>\r\n                                            <td class="text-center coluna_5">41,55</td>\r\n                                            <td class="text-center coluna_6">0,39</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">13/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,61</td>\r\n                                            <td class="text-center coluna_4">28,80</td>\r\n                                            <td class="text-center coluna_5">41,35</td>\r\n                                            <td class="text-center coluna_6">0,36</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">14/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,59</td>\r\n                                            <td class="text-center coluna_4">28,67</td>\r\n                                            <td class="text-center coluna_5">41,16</td>\r\n                                            <td class="text-center coluna_6">0,76</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">15/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,57</td>\r\n                                            <td class="text-center coluna_4">28,53</td>\r\n                                            <td class="text-center coluna_5">40,97</td>\r\n                                            <td class="text-center coluna_6">0,53</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">16/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,54</td>\r\n                                            <td class="text-center coluna_4">28,33</td>\r\n                                            <td class="text-center coluna_5">40,67</td>\r\n                                            <td class="text-center coluna_6">0,59</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">17/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,50</td>\r\n                                            <td class="text-center coluna_4">28,06</td>\r\n                                            <td class="text-center coluna_5">40,29</td>\r\n                                            <td class="text-center coluna_6">0,57</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">18/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,44</td>\r\n                                            <td class="text-center coluna_4">27,66</td>\r\n                                            <td class="text-center coluna_5">39,72</td>\r\n                                            <td class="text-center coluna_6">0,37</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">19/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,46</td>\r\n                                            <td class="text-center coluna_4">27,80</td>\r\n                                            <td class="text-center coluna_5">39,91</td>\r\n                                            <td class="text-center coluna_6">0,60</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">20/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                                            <td class="text-center coluna_3">816,48</td>\r\n                                            <td class="text-center coluna_4">27,93</td>\r\n                                            <td class="text-center coluna_5">40,10</td>\r\n                                            <td class="text-center coluna_6">1,08</td>\r\n                                            <td class="text-center coluna_7">5,50</td>\r\n                                            <td class="text-center coluna_8">21/08/2025</td>\r\n\r\n                                        </tr>\r\n                                        ', '>\r\n                                            <td class="text-center coluna_1">29002</td>\r\n                                            <td class="text-center coluna_2">CACHOEIRA                                         </td>\r\n                    

In [12]:
print(len(data['html']))

41581

In [14]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.13.5-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading beautifulsoup4-4.13.5-py3-none-any.whl (105 kB)
Downloading soupsieve-2.8-py3-none-any.whl (36 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, soupsieve, beautifulsoup4

   ------------- -------------------------- 1/3 [soupsieve]
   ------------- -------------------------- 1/3 [soupsieve]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   ---------------------------------------- 3/3 [beautifulsoup4]

Successfully installed beautifulsoup4-4.13.5 soupsieve-2.8 typing-extensions-4.15.0

In [18]:
import pandas as pd
from bs4 import BeautifulSoup
import json

# Seu JSON contendo o HTML
json_data = data

# 1. Extrair o conteúdo HTML do JSON
html_content = json_data['html']

# 2. Analisar (parse) o HTML com Beautiful Soup
soup = BeautifulSoup(html_content, 'html.parser')

# 3. Encontrar a tabela de dados
# A tabela pode ser identificada por suas classes CSS
table = soup.find('table', class_='table-striped')

# 4. Extrair os cabeçalhos (cabeçalhos das colunas)
headers = [header.get_text(strip=True) for header in table.find('thead').find_all('th')]

# 5. Extrair as linhas de dados da tabela
rows = []
# Itera sobre cada tag <tr> (linha) no corpo (tbody) da tabela
for row in table.find('tbody').find_all('tr'):
    # Extrai o texto de cada célula <td> e remove espaços em branco
    cols = [col.get_text(strip=True) for col in row.find_all('td')]
    rows.append(cols)

# 6. Criar o DataFrame do Pandas
df = pd.DataFrame(rows, columns=headers)

# 7. Limpeza e conversão de tipos de dados (passo recomendado)
# Colunas que precisam ser convertidas para numéricas
numeric_cols = [
    'Cota (m)', 'Volume Útil (hm³)', 'Volume Útil (%)',
    'Afluência (m³/s)', 'Defluência (m³/s)'
]

for col in numeric_cols:
    # Substitui a vírgula por ponto e converte para float
    df[col] = df[col].str.replace(',', '.', regex=False).astype(float)

# Converte a coluna de data para o tipo datetime
df['Data da Medição'] = pd.to_datetime(df['Data da Medição'], format='%d/%m/%Y')

# Converte o código para inteiro
df['Código do Reservatório'] = df['Código do Reservatório'].astype(int)

# Remove espaços extras da coluna de nome
df['Reservatório'] = df['Reservatório'].str.strip()


# Exibir o resultado
print("### DataFrame Criado com Sucesso ###")
print(df.head()) # Mostra as primeiras 5 linhas
print("\n### Informações do DataFrame (Tipos de Dados) ###")
df.info()

### DataFrame Criado com Sucesso ###
   Código do Reservatório Reservatório  Cota (m)  Volume Útil (hm³)  \
0                   29002    CACHOEIRA    816.56              28.47
1                   29002    CACHOEIRA    816.58              28.60
2                   29002    CACHOEIRA    816.58              28.60
3                   29002    CACHOEIRA    816.58              28.60
4                   29002    CACHOEIRA    816.57              28.53

   Volume Útil (%)  Afluência (m³/s)  Defluência (m³/s) Data da Medição
0            40.87              0.92                4.5      2025-08-01
1            41.06              1.75                4.5      2025-08-02
2            41.06              0.23                4.5      2025-08-03
3            41.06              0.33                4.5      2025-08-04
4            40.97              0.14                4.5      2025-08-05

### Informações do DataFrame (Tipos de Dados) ###
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Código do Reservatório  26 non-null     int64
 1   Reservatório            26 non-null     object
 2   Cota (m)                26 non-null     float64
 3   Volume Útil (hm³)       26 non-null     float64
 4   Volume Útil (%)         26 non-null     float64
 5   Afluência (m³/s)        26 non-null     float64
 6   Defluência (m³/s)       26 non-null     float64
 7   Data da Medição         26 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 1.8+ KB

In [19]:
display(df)

,Código do Reservatório,Reservatório,Cota (m),Volume Útil (hm³),Volume Útil (%),Afluência (m³/s),Defluência (m³/s),Data da Medição
0,29002,CACHOEIRA,816.56,28.47,40.87,0.92,4.50,2025-08-01
1,29002,CACHOEIRA,816.58,28.60,41.06,1.75,4.50,2025-08-02
2,29002,CACHOEIRA,816.58,28.60,41.06,0.23,4.50,2025-08-03
3,29002,CACHOEIRA,816.58,28.60,41.06,0.33,4.50,2025-08-04
4,29002,CACHOEIRA,816.57,28.53,40.97,0.14,4.50,2025-08-05
5,29002,CACHOEIRA,816.55,28.40,40.77,0.29,4.54,2025-08-06
6,29002,CACHOEIRA,816.59,28.66,41.15,0.74,5.00,2025-08-07
7,29002,CACHOEIRA,816.61,28.82,41.38,0.14,5.00,2025-08-08
8,29002,CACHOEIRA,816.62,28.87,41.45,0.13,5.04,2025-08-09
9,29002,CACHOEIRA,816.62,28.87,41.45,0.14,5.50,2025-08-10
10,29002,CACHOEIRA,816.62,28.87,41.45,0.50,5.50,2025-08-11
11,29002,CACHOEIRA,816.65,29.07,41.74,0.28,5.50,2025-08-12
12,29002,CACHOEIRA,816.63,28.94,41.55,0.39,5.50,2025-08-13
13,29002,CACHOEIRA,816.61,28.80,41.35,0.36,5.50,2025-08-14
14,29002,CACHOEIRA,816.59,28.67,41.16,0.76,5.50,2025-08-15
15,29002,CACHOEIRA,816.57,28.53,40.97,0.53,5.50,2025-08-16
16,29002,CACHOEIRA,816.54,28.33,40.67,0.59,5.50,2025-08-17
17,29002,CACHOEIRA,816.50,28.06,40.29,0.57,5.50,2025-08-18
18,29002,CACHOEIRA,816.44,27.66,39.72,0.37,5.50,2025-08-19
19,29002,CACHOEIRA,816.46,27.80,39.91,0.60,5.50,2025-08-20
20,29002,CACHOEIRA,816.48,27.93,40.10,1.08,5.50,2025-08-21
21,29002,CACHOEIRA,816.48,27.93,40.10,1.36,5.50,2025-08-22
22,29002,CACHOEIRA,816.52,28.20,40.49,0.53,5.50,2025-08-23
23,29002,CACHOEIRA,816.56,28.47,40.87,2.29,5.50,2025-08-24
24,29002,CACHOEIRA,816.58,28.60,41.06,0.55,5.50,2025-08-25
25,29002,CACHOEIRA,816.58,28.60,41.06,1.25,5.50,2025-08-26

In [ ]:
    url = (
        "https://www.ana.gov.br/sar0/MedicaoCantareira"
        "?dropDownListReservatorios=29002"
        "&dataInicial=01%2F08%2F2025"
        "&dataFinal=25%2F08%2F2025"
    )
    data = fetch_page_as_json(url)

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime
import time
from dateutil.relativedelta import relativedelta

def gerar_periodos_mensais(data_inicial, data_final):
    """
    Gera uma lista de tuplas (inicio_mes, fim_mes) para um intervalo de datas.
    Respeita a regra de buscar um mês de cada vez.
    """
    periodos = []
    data_corrente = data_inicial
    
    while data_corrente < data_final:
        # O início do período é o primeiro dia do mês corrente
        inicio_periodo = data_corrente.replace(day=1)
        
        # O fim do período é o último dia do mesmo mês
        fim_periodo = inicio_periodo + relativedelta(months=1) - relativedelta(days=1)
        
        # Garante que o fim do período não ultrapasse a data final geral
        if fim_periodo > data_final:
            fim_periodo = data_final
            
        periodos.append((inicio_periodo, fim_periodo))
        
        # Avança para o próximo mês
        data_corrente = inicio_periodo + relativedelta(months=1)
        
    return periodos

def buscar_e_converter_dados(reservatorio_id, data_inicial, data_final):
    """
    Busca os dados de um reservatório para um período específico,
    analisa o HTML e retorna um DataFrame do Pandas.
    """
    base_url = "https://www.ana.gov.br/sar0/MedicaoCantareira"
    
    # Formata as datas para o formato esperado pela URL (dd/mm/yyyy)
    params = {
        'dropDownListReservatorios': reservatorio_id,
        'dataInicial': data_inicial.strftime('%d/%m/%Y'),
        'dataFinal': data_final.strftime('%d/%m/%Y')
    }
    
    try:
        response = requests.get(base_url, params=params, timeout=30)
        response.raise_for_status()  # Lança exceção para erros HTTP (4xx ou 5xx)
    except requests.exceptions.RequestException as e:
        print(f"Erro ao fazer a requisição para o período {params['dataInicial']} - {params['dataFinal']}: {e}")
        return pd.DataFrame() # Retorna DataFrame vazio em caso de erro

    # Analisa o HTML com BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Encontra a tabela de dados
    table = soup.find('table', class_='table-striped')

    # Se não houver tabela na página, retorna um DataFrame vazio
    if not table:
        return pd.DataFrame()

    # Extrai os cabeçalhos
    headers = [header.get_text(strip=True) for header in table.find('thead').find_all('th')]
    
    # Extrai as linhas de dados
    rows = []
    for row in table.find('tbody').find_all('tr'):
        cols = [col.get_text(strip=True) for col in row.find_all('td')]
        if cols: # Garante que a linha não está vazia
            rows.append(cols)

    if not rows:
        return pd.DataFrame()

    # Cria o DataFrame
    df = pd.DataFrame(rows, columns=headers)

    # --- Limpeza e conversão de tipos de dados ---
    numeric_cols = [
        'Cota (m)', 'Volume Útil (hm³)', 'Volume Útil (%)',
        'Afluência (m³/s)', 'Defluência (m³/s)'
    ]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = df[col].str.replace(',', '.', regex=False).astype(float)

    df['Data da Medição'] = pd.to_datetime(df['Data da Medição'], format='%d/%m/%Y')
    df['Código do Reservatório'] = df['Código do Reservatório'].astype(int)
    df['Reservatório'] = df['Reservatório'].str.strip()
    
    return df

def main():
    """
    Função principal para orquestrar o scraping de dados históricos.
    """
    RESERVATORIO_ID = 29002  # Cachoeira
    DATA_INICIAL_GERAL = datetime(2000, 1, 1)
    DATA_FINAL_GERAL = datetime(2025, 9, 10)

    print(f"Iniciando coleta de dados para o reservatório ID {RESERVATORIO_ID}")
    print(f"Período total: de {DATA_INICIAL_GERAL.strftime('%d/%m/%Y')} a {DATA_FINAL_GERAL.strftime('%d/%m/%Y')}\n")

    # 1. Gera todos os períodos mensais a serem consultados
    periodos_de_busca = gerar_periodos_mensais(DATA_INICIAL_GERAL, DATA_FINAL_GERAL)
    
    lista_de_dataframes = []

    # 2. Itera sobre cada período, busca os dados e armazena
    for inicio, fim in periodos_de_busca:
        print(f"Buscando dados de: {inicio.strftime('%d/%m/%Y')} a {fim.strftime('%d/%m/%Y')}...")
        
        df_mensal = buscar_e_converter_dados(RESERVATORIO_ID, inicio, fim)
        if not df_mensal.empty:
            lista_de_dataframes.append(df_mensal)
            print(f"-> {len(df_mensal)} registros encontrados.")
        else:
            print("-> Nenhum registro encontrado para este período.")
            
        # Pausa para ser gentil com o servidor
        time.sleep(0.5) 

    # 3. Concatena todos os DataFrames em um só
    if lista_de_dataframes:
        df_final = pd.concat(lista_de_dataframes, ignore_index=True)
        print("\n\n--- Coleta Finalizada com Sucesso! ---")
        print("Resumo do DataFrame final:")
        df_final.info()
        
        print("\nPrimeiros 5 registros:")
        print(df_final.head())
        
        print("\nÚltimos 5 registros:")
        print(df_final.tail())
        
        # Opcional: Salvar os dados em um arquivo CSV para uso futuro
        # nome_arquivo = f"dados_reservatorio_{RESERVATORIO_ID}.csv"
        # df_final.to_csv(nome_arquivo, index=False)
        # print(f"\nDados salvos em '{nome_arquivo}'")

    else:
        print("\nNenhum dado foi coletado no período especificado.")


main()

Iniciando coleta de dados para o reservatório ID 29002
Período total: de 01/01/2000 a 10/09/2025

Buscando dados de: 01/01/2000 a 31/01/2000...

,Código do Reservatório,Reservatório,Cota (m),Volume Útil (hm³),Volume Útil (%),Afluência (m³/s),Defluência (m³/s),Data da Medição
0,29002,CACHOEIRA,815.78,24.44,34.64,4.66,5.96,2000-01-01
1,29002,CACHOEIRA,815.77,24.37,34.54,3.69,5.96,2000-01-02
2,29002,CACHOEIRA,815.94,25.51,36.16,11.98,3.07,2000-01-03
3,29002,CACHOEIRA,816.14,26.87,38.08,15.40,2.12,2000-01-04
4,29002,CACHOEIRA,816.43,28.86,40.90,23.03,2.12,2000-01-05
5,29002,CACHOEIRA,816.72,30.87,43.76,24.82,2.19,2000-01-06
6,29002,CACHOEIRA,816.89,32.07,45.45,14.95,2.22,2000-01-07
7,29002,CACHOEIRA,817.08,33.41,47.36,16.44,2.25,2000-01-08
8,29002,CACHOEIRA,817.20,34.27,48.57,9.99,2.27,2000-01-09
9,29002,CACHOEIRA,817.16,33.98,48.17,9.76,2.27,2000-01-10
10,29002,CACHOEIRA,817.12,33.70,47.76,4.97,2.27,2000-01-11
11,29002,CACHOEIRA,817.14,33.84,47.97,2.61,2.26,2000-01-12
12,29002,CACHOEIRA,817.18,34.13,48.37,3.97,2.26,2000-01-13
13,29002,CACHOEIRA,817.22,34.41,48.78,3.58,2.27,2000-01-14
14,29002,CACHOEIRA,817.26,34.70,49.18,3.60,2.28,2000-01-15
15,29002,CACHOEIRA,817.30,34.99,49.59,3.71,2.28,2000-01-16
16,29002,CACHOEIRA,817.31,35.06,49.69,1.32,2.29,2000-01-17
17,29002,CACHOEIRA,817.33,35.20,49.90,2.36,2.29,2000-01-18
18,29002,CACHOEIRA,817.34,35.28,50.00,2.32,2.29,2000-01-19
19,29002,CACHOEIRA,817.36,35.42,50.20,1.66,2.29,2000-01-20
20,29002,CACHOEIRA,817.38,35.56,50.41,2.36,2.29,2000-01-21
21,29002,CACHOEIRA,817.38,35.56,50.41,1.20,2.30,2000-01-22
22,29002,CACHOEIRA,817.38,35.56,50.41,1.70,2.30,2000-01-23
23,29002,CACHOEIRA,817.37,35.49,50.31,1.36,2.30,2000-01-24
24,29002,CACHOEIRA,817.35,35.35,50.10,1.22,2.29,2000-01-25
25,29002,CACHOEIRA,817.33,35.20,49.90,1.03,2.29,2000-01-26
26,29002,CACHOEIRA,817.39,35.64,50.51,7.70,2.29,2000-01-27
27,29002,CACHOEIRA,817.43,35.93,50.92,6.05,2.30,2000-01-28
28,29002,CACHOEIRA,817.43,35.93,50.92,2.80,2.30,2000-01-29
29,29002,CACHOEIRA,817.42,35.85,50.82,2.26,2.30,2000-01-30
30,29002,CACHOEIRA,817.40,35.71,50.61,1.53,2.30,2000-01-31
31,29002,CACHOEIRA,817.40,35.71,50.61,3.30,2.30,2000-02-01

-> 32 registros encontrados.
Buscando dados de: 01/02/2000 a 29/02/2000...

,Código do Reservatório,Reservatório,Cota (m),Volume Útil (hm³),Volume Útil (%),Afluência (m³/s),Defluência (m³/s),Data da Medição
0,29002,CACHOEIRA,817.40,35.71,50.61,3.30,2.30,2000-02-01
1,29002,CACHOEIRA,817.55,36.80,52.15,11.20,2.31,2000-02-02
2,29002,CACHOEIRA,817.57,36.94,52.36,5.81,2.32,2000-02-03
3,29002,CACHOEIRA,817.57,36.94,52.36,1.82,2.32,2000-02-04
4,29002,CACHOEIRA,817.58,37.02,52.46,3.56,2.32,2000-02-05
5,29002,CACHOEIRA,817.58,37.02,52.46,2.62,2.32,2000-02-06
6,29002,CACHOEIRA,817.57,36.94,52.36,1.98,2.32,2000-02-07
7,29002,CACHOEIRA,817.54,36.72,52.05,2.49,2.32,2000-02-08
8,29002,CACHOEIRA,817.52,36.58,51.85,1.43,2.31,2000-02-09
9,29002,CACHOEIRA,817.56,36.87,52.26,6.58,2.31,2000-02-10
10,29002,CACHOEIRA,817.67,37.67,53.40,14.81,2.32,2000-02-11
11,29002,CACHOEIRA,817.66,37.60,53.29,13.88,2.33,2000-02-12
12,29002,CACHOEIRA,817.69,37.82,53.60,16.97,2.33,2000-02-13
13,29002,CACHOEIRA,817.76,38.33,54.33,16.28,2.34,2000-02-14
14,29002,CACHOEIRA,817.81,38.70,54.85,10.80,2.35,2000-02-15
15,29002,CACHOEIRA,817.86,39.07,55.37,9.91,2.35,2000-02-16
16,29002,CACHOEIRA,817.93,39.59,56.11,14.55,2.36,2000-02-17
17,29002,CACHOEIRA,817.98,39.96,56.63,16.86,2.37,2000-02-18
18,29002,CACHOEIRA,818.00,40.10,56.84,14.59,2.37,2000-02-19
19,29002,CACHOEIRA,817.97,39.88,56.53,9.79,2.37,2000-02-20
20,29002,CACHOEIRA,817.95,39.73,56.32,7.96,2.37,2000-02-21
21,29002,CACHOEIRA,817.94,39.66,56.21,7.00,2.36,2000-02-22
22,29002,CACHOEIRA,817.91,39.44,55.90,4.89,2.36,2000-02-23
23,29002,CACHOEIRA,817.89,39.29,55.69,5.65,2.36,2000-02-24
24,29002,CACHOEIRA,817.90,39.36,55.79,8.02,2.36,2000-02-25
25,29002,CACHOEIRA,817.91,39.44,55.90,7.73,2.18,2000-02-26
26,29002,CACHOEIRA,817.91,39.44,55.90,6.67,2.17,2000-02-27
27,29002,CACHOEIRA,817.90,39.36,55.79,5.72,2.17,2000-02-28
28,29002,CACHOEIRA,817.90,39.36,55.79,6.37,2.17,2000-02-29
29,29002,CACHOEIRA,817.93,39.59,56.11,8.84,2.17,2000-03-01

-> 30 registros encontrados.
Buscando dados de: 01/03/2000 a 31/03/2000...

,Código do Reservatório,Reservatório,Cota (m),Volume Útil (hm³),Volume Útil (%),Afluência (m³/s),Defluência (m³/s),Data da Medição
0,29002,CACHOEIRA,817.93,39.59,56.11,8.84,2.17,2000-03-01
1,29002,CACHOEIRA,817.96,39.81,56.42,8.84,2.17,2000-03-02
2,29002,CACHOEIRA,817.98,39.96,56.63,9.58,2.17,2000-03-03
3,29002,CACHOEIRA,817.99,40.03,56.74,8.83,2.17,2000-03-04
4,29002,CACHOEIRA,817.99,40.03,56.74,7.87,2.17,2000-03-05
5,29002,CACHOEIRA,818.02,40.25,57.05,9.86,2.18,2000-03-06
6,29002,CACHOEIRA,818.00,40.10,56.84,6.56,2.18,2000-03-07
7,29002,CACHOEIRA,818.04,40.40,57.26,11.82,2.18,2000-03-08
8,29002,CACHOEIRA,818.10,40.85,57.90,13.65,2.18,2000-03-09
9,29002,CACHOEIRA,818.12,41.00,58.11,10.22,2.19,2000-03-10
10,29002,CACHOEIRA,818.15,41.22,58.43,10.93,2.03,2000-03-11
11,29002,CACHOEIRA,818.23,41.82,59.28,12.03,2.00,2000-03-12
12,29002,CACHOEIRA,818.26,42.05,59.60,7.42,2.01,2000-03-13
13,29002,CACHOEIRA,818.29,42.27,59.92,7.12,2.01,2000-03-14
14,29002,CACHOEIRA,818.28,42.20,59.81,4.94,2.01,2000-03-15
15,29002,CACHOEIRA,818.28,42.20,59.81,7.21,2.01,2000-03-16
16,29002,CACHOEIRA,818.28,42.20,59.81,7.21,2.01,2000-03-17
17,29002,CACHOEIRA,818.29,42.27,59.92,8.08,2.01,2000-03-18
18,29002,CACHOEIRA,818.32,42.50,60.24,9.93,2.01,2000-03-19
19,29002,CACHOEIRA,818.33,42.57,60.34,8.18,2.01,2000-03-20
20,29002,CACHOEIRA,818.34,42.65,60.45,8.18,2.01,2000-03-21
21,29002,CACHOEIRA,818.35,42.72,60.56,8.19,2.02,2000-03-22
22,29002,CACHOEIRA,818.34,42.65,60.45,8.95,2.02,2000-03-23
23,29002,CACHOEIRA,818.35,42.72,60.56,10.79,2.02,2000-03-24
24,29002,CACHOEIRA,818.32,42.50,60.24,7.30,2.01,2000-03-25
25,29002,CACHOEIRA,818.28,42.20,59.81,6.43,2.01,2000-03-26
26,29002,CACHOEIRA,818.25,41.97,59.49,7.20,2.01,2000-03-27
27,29002,CACHOEIRA,818.24,41.90,59.38,8.94,2.01,2000-03-28
28,29002,CACHOEIRA,818.31,42.42,60.13,20.90,2.01,2000-03-29
29,29002,CACHOEIRA,818.39,43.03,60.98,11.50,2.02,2000-03-30
30,29002,CACHOEIRA,818.39,43.03,60.98,13.02,2.02,2000-03-31
31,29002,CACHOEIRA,818.36,42.80,60.66,13.10,2.02,2000-04-01

-> 32 registros encontrados.
Buscando dados de: 01/04/2000 a 30/04/2000...

KeyboardInterrupt:

In [15]:
import pandas as pd

dados = pd.read_csv('dados_reservatorio.csv')
dados['Data da Medição'] = pd.to_datetime(dados['Data da Medição'], format='%Y-%m-%d')
dados

,Código do Reservatório,Reservatório,Cota (m),Volume Útil (hm³),Volume Útil (%),Afluência (m³/s),Defluência (m³/s),Data da Medição
0,29002,CACHOEIRA,815.78,24.44,34.64,4.66,5.96,2000-01-01
1,29002,CACHOEIRA,815.77,24.37,34.54,3.69,5.96,2000-01-02
2,29002,CACHOEIRA,815.94,25.51,36.16,11.98,3.07,2000-01-03
3,29002,CACHOEIRA,816.14,26.87,38.08,15.40,2.12,2000-01-04
4,29002,CACHOEIRA,816.43,28.86,40.90,23.03,2.12,2000-01-05
...,...,...,...,...,...,...,...,...
9663,29002,CACHOEIRA,817.17,32.63,46.85,0.21,5.50,2025-09-12
9664,29002,CACHOEIRA,817.21,32.91,47.25,0.56,5.50,2025-09-13
9665,29002,CACHOEIRA,817.23,33.05,47.45,0.10,5.50,2025-09-14
9666,29002,CACHOEIRA,817.25,33.17,47.63,0.15,5.50,2025-09-15
9667,29002,CACHOEIRA,817.24,33.12,47.55,0.16,5.50,2025-09-16

# Análise de dados

## Primeira Análise

- Análise de evolução temporal das features. Principal pra gente é a cota, mas vamos olhar todas.

In [22]:
df = dados.drop(['Código do Reservatório', 'Reservatório'], axis=1)

In [32]:
df['Entrada_Liquida (m³/s)'] = df['Afluência (m³/s)'] - df['Defluência (m³/s)']

In [33]:
import pandas as pd
import numpy as np
import plotly.express as px



# --- Passo 2: Transformar o DataFrame para o formato longo ---
# Esta é a etapa chave para plotar com Plotly Express de forma eficiente.
# 'id_vars' é a coluna que será mantida como eixo x.
# As outras colunas serão transformadas em linhas.
df_longo = df.melt(id_vars='Data da Medição',
                     var_name='Variável',
                     value_name='Valor')


# --- Passo 3: Criar o gráfico de linhas interativo ---
# O argumento 'color' é o que agrupa os dados e cria uma linha para cada
# variável, adicionando-as à legenda interativa.
fig = px.line(
    df_longo,
    x='Data da Medição',
    y='Valor',
    color='Variável', # Agrupa e colore as linhas pela coluna 'Variável'
    title='Análise Temporal de Variáveis do Reservatório',
    labels={
        'Data da Medição': 'Data',
        'Valor': 'Valores',
        'Variável': 'Selecione a Variável'
    },
    hover_name='Variável',
    template='plotly_white' # Um template visualmente agradável
)

# --- Passo 4: Melhorias e customização (Opcional) ---
# Melhora a dica de ferramenta (tooltip) para mostrar todas as variáveis
# para uma data específica ao passar o mouse.
fig.update_layout(
    hovermode='x unified',
    legend_title_text='Variáveis'
)
fig.update_traces(
    hovertemplate='<b>Valor:</b> %{y}<extra></extra>'
)


# --- Passo 5: Exibir o gráfico ---
# Em ambientes como Jupyter Notebook ou Google Colab, isso abrirá o gráfico
# interativo diretamente na célula.
fig.show()

In [34]:
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler()
cols = [i for i in df.columns if i != 'Data da Medição'] 
df_scaler = scaler.fit_transform(df[cols])
df_scaler = pd.DataFrame(df_scaler, columns=cols)
df_scaler['Data da Medição'] = df['Data da Medição']



# --- Passo 2: Transformar o DataFrame para o formato longo ---
# Esta é a etapa chave para plotar com Plotly Express de forma eficiente.
# 'id_vars' é a coluna que será mantida como eixo x.
# As outras colunas serão transformadas em linhas.

df_longo = df_scaler.melt(id_vars='Data da Medição',
                     var_name='Variável',
                     value_name='Valor')


# --- Passo 3: Criar o gráfico de linhas interativo ---
# O argumento 'color' é o que agrupa os dados e cria uma linha para cada
# variável, adicionando-as à legenda interativa.
fig = px.line(
    df_longo,
    x='Data da Medição',
    y='Valor',
    color='Variável', # Agrupa e colore as linhas pela coluna 'Variável'
    title='Análise Temporal de Variáveis do Reservatório',
    labels={
        'Data da Medição': 'Data',
        'Valor': 'Valores',
        'Variável': 'Selecione a Variável'
    },
    hover_name='Variável',
    template='plotly_white' # Um template visualmente agradável
)

# --- Passo 4: Melhorias e customização (Opcional) ---
# Melhora a dica de ferramenta (tooltip) para mostrar todas as variáveis
# para uma data específica ao passar o mouse.
fig.update_layout(
    hovermode='x unified',
    legend_title_text='Variáveis'
)
fig.update_traces(
    hovertemplate='<b>Valor:</b> %{y}<extra></extra>'
)


# --- Passo 5: Exibir o gráfico ---
# Em ambientes como Jupyter Notebook ou Google Colab, isso abrirá o gráfico
# interativo diretamente na célula.
fig.show()

## Estruturação possível para analise de series temporais da Cota -> VOLUME DO RESERVATÓRIO
- Utilizar as variáveis de afluencia e defluencia como variáveis exoginas da serie temporal.
- Utilizar delay das variáveis exoginas para prever a serie temporal da cota
- Determinar a janela que quero prever -> Teste
- No treino e teste, saber fazer k-fold para series temporais, isto é:
- - Ordenar os dados pela data
- - fazer partições ordenadas
- - mostrar um pedaço que seria o treino, não mostrar pedaço qeu é o teste e deixar um pedaço de fora
- - Fazer isso, até percorrer dataset todo
- Avaliar tempo útil para previsão, isto é, será que olhar 25 anos de reservatório para prever o futuro, faz sentido? Ou a análise dos últmos 5 anos é suficiente? (em 25 anos, há modificação estrutural?) -> Fazer partições anuais, para ver quanto de defluencia teve nos anos (há um aumento grande?) -> mesma coisa para afluencia

## Motivação:
-  A cota do reservatório é uma medida direta da altura da água, que está diretamente relacionada ao volume de água armazenado. Analisar a cota ao longo do tempo pode fornecer insights valiosos sobre o comportamento do reservatório, como variações sazonais, tendências de longo prazo e respostas a eventos climáticos.

# Adicionando coluna de chuva e alterando local de base de dados

In [ ]:
# ==============================================================================
# 1. IMPORTS E CONFIGURAÇÕES
# ==============================================================================
import os
import json
import time
import zlib  # Essencial para descompactar a resposta da API
import requests
import pandas as pd
from datetime import date, datetime
import calendar

# A nova API usa um certificado SSL que pode falhar na verificação.
# O código abaixo desativa os avisos de segurança ao usar `verify=False`.
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

print("Bibliotecas importadas e configuração concluída.")

# ==============================================================================
# 2. PARÂMETROS DA CONSULTA
# ==============================================================================
#DATA_INICIO = date(2000, 1, 1)
DATA_INICIO = date(2017, 10, 1)
DATA_FIM = date(2025, 9, 16)
SISTEMA_ID = 0  # 0 = Sistema Cantareira

# ==============================================================================
# 3. FUNÇÕES DA NOVA DOCUMENTAÇÃO (Refatoradas para maior clareza)
# ==============================================================================

def get_json(url):
    """
    Busca os dados na API e retorna o JSON.
    A API agora envia JSON puro, então a descompressão com zlib não é mais necessária.
    """
    try:
        print(f"  Fazendo requisição para: {url}")
        r = requests.get(url, verify=False, timeout=60)
        r.raise_for_status()  # Verifica se houve erro na requisição (4xx ou 5xx)
        
        # A MUDANÇA ESTÁ AQUI: Usamos o método .json() direto da resposta
        data = r.json() 
        
        return json.dumps(data) # json.dumps ainda é útil para manter a estrutura
    except requests.exceptions.RequestException as e:
        print(f"  !!! Erro de requisição: {e}")
        return None
    except json.JSONDecodeError as e:
        print(f"  !!! Erro ao decodificar JSON. A resposta não parece ser um JSON válido: {e}")
        print(f"      Conteúdo recebido: {r.text[:200]}") # Mostra o início da resposta
        return None

def json2df(jsn):
    df = pd.read_json(jsn)
    return df.drop(['FlagHasError', 'Message'], axis=1, errors='ignore')

def rename_field(x):
    return str(x).replace('/', '-').replace(' (', '-').replace('-', '_').replace(')', '').replace('Cesp', 'CESP').replace('Represa ', '').replace(' ', '')

def list_represas(df):
    lst = df.loc['ListaRepresas']['ReturnObj']
    df_represas = pd.json_normalize(lst)
    return df_represas.drop(['temChuva','temNivel', 'temQjus', 'temQnat', 'temVolume'], axis=1, errors='ignore')

def safe_merge(df_full, df_new):
    """Função auxiliar para fazer o merge de forma segura, tratando o primeiro caso."""
    if df_full.empty:
        return df_new
    else:
        # Usar how='outer' para não perder dados se as datas não alinharem perfeitamente
        return pd.merge(df_full, df_new, on='Data', how='outer')

def list_volumes(df):
    lst = df.loc['ListaDados']['ReturnObj']
    
    # --- NOVA CORREÇÃO APLICADA AQUI ---
    # Iteramos manualmente para criar uma lista "limpa" de registros,
    # ignorando qualquer valor 'None' que apareça dentro da lista 'Dados'.
    records_limpos = []
    for item_diario in lst:
        # Pula dias que não têm a lista 'Dados'
        if not isinstance(item_diario.get('Dados'), list):
            continue
        # Pega apenas os dicionários válidos de dentro da lista 'Dados'
        for record in item_diario['Dados']:
            if isinstance(record, dict):
                records_limpos.append(record)

    # Se não houver nenhum registro válido, retorna um DataFrame vazio
    if not records_limpos:
        return pd.DataFrame()
    
    # Cria o DataFrame a partir da lista de registros já limpa e plana
    df_normalized = pd.DataFrame(records_limpos)
    # --- FIM DA CORREÇÃO ---

    fields = sorted(list(set(df_normalized['Nome'])))
    df_full = pd.DataFrame()

    for field_name in fields:
        j = rename_field(field_name)
        temp_df = df_normalized[df_normalized['Nome'] == field_name].copy()
        temp_df.drop(['FlagConsolidado', 'NAMaxMax', 'NAMinMin', 'QJusanteMax', 'QJusanteMin', 'NivelUltimoDia', 'SistemaId', 'ComponenteId', 'UltimoDia', 'VazaoJusantePrincipal', 'VazaoJusanteSecundaria', 'VolumeOperacionalUltimoDia', 'VolumePorcentagemUltimoDia', 'VolumeTotalUltimoDia', 'Nome'], axis=1, errors='ignore', inplace=True)
        temp_df.columns = [col if col == 'Data' else f"{j}_{col}" for col in temp_df.columns]
        temp_df['Data'] = pd.to_datetime(temp_df['Data'])
        df_full = safe_merge(df_full, temp_df)
    
    if not df_full.empty:
        df_full.set_index('Data', inplace=True)
    return df_full

def list_vazao(df):
    df_represas = list_represas(df)
    lst = df.loc['ListaDados']['ReturnObj']

    # --- NOVA CORREÇÃO APLICADA AQUI ---
    # Lógica idêntica à de list_volumes, mas para a chave 'Qnat'
    records_limpos = []
    for item_diario in lst:
        if not isinstance(item_diario.get('Qnat'), list):
            continue
        for record in item_diario['Qnat']:
            if isinstance(record, dict):
                records_limpos.append(record)

    if not records_limpos:
        return pd.DataFrame()
        
    df_normalized = pd.DataFrame(records_limpos)
    # --- FIM DA CORREÇÃO ---
    
    df_merged = pd.merge(df_normalized, df_represas, on='ComponenteId', how='outer')
    fields = sorted(list(set(df_merged['Nome'].dropna())))
    df_full = pd.DataFrame()

    for field_name in fields:
        j = rename_field(field_name)
        temp_df = df_merged[df_merged['Nome'] == field_name].copy()
        temp_df.drop(['ComponenteId', 'Nome', 'VazaoAfluenteMax', 'VazaoAfluenteMin', 'VazaoNaturalMax', 'VazaoNaturalMin'], axis=1, errors='ignore', inplace=True)
        temp_df.columns = [col if col == 'Data' else f"{j}_{col}" for col in temp_df.columns]
        temp_df['Data'] = pd.to_datetime(temp_df['Data'])
        df_full = safe_merge(df_full, temp_df)
        
    if not df_full.empty:
        df_full.set_index('Data', inplace=True)
    return df_full

def list_SE(df):
    lst = df.loc['ListaDados']['ReturnObj']
    df_se = pd.json_normalize(lst)
    df_se.drop(['Dados', 'Data', 'Qnat'], axis=1, errors='ignore', inplace=True)
    col = [f"SE_{c}" for c in df_se.columns]
    col = [c.replace('SistemaEquivalente.', '').replace('SE_Data', 'Data') for c in col]
    df_se.columns = col
    df_se['Data'] = pd.to_datetime(df_se['Data'])
    df_se.set_index('Data', inplace=True)
    return df_se

def list_SC(df):
    lst = df.loc['ListaDadosSistema']['ReturnObj']
    df_sc = pd.json_normalize(lst)
    df_sc.drop(['objSistema.SistemaId', 'objQETA', 'objSistema.Data'], axis=1, errors='ignore', inplace=True)
    col = [f"SC_{c}".replace('objSistema', '').replace('.', '') for c in df_sc.columns]
    col = [c.replace('SC_Data', 'Data') for c in col]
    df_sc.columns = col
    df_sc['Data'] = pd.to_datetime(df_sc['Data'])
    df_sc.set_index('Data', inplace=True)
    return df_sc

def list_vazaoestruturas(df):
    lst = df.loc['ListaDadosLocais']['ReturnObj']
    list_d = [parte2 for parte1 in lst for parte2 in parte1['Dados'] if isinstance(parte2, dict)]
    if not list_d: return pd.DataFrame()
    df_normalized = pd.DataFrame(list_d)
    fields = sorted(list(set(df_normalized['Abreviatura'])))
    df_full = pd.DataFrame()

    for field_name in fields:
        j = rename_field(field_name)
        temp_df = df_normalized[df_normalized['Abreviatura'] == field_name].copy()
        temp_df.drop(['Maximo', 'Minimo', 'Dia', 'Abreviatura', 'ComponenteId', 'LocalMedicaoId', 'Nome', 'SistemaId'], axis=1, errors='ignore', inplace=True)
        temp_df.columns = [col if col == 'Data' else f"{j}_{col}" for col in temp_df.columns]
        temp_df['Data'] = pd.to_datetime(temp_df['Data'])
        df_full = safe_merge(df_full, temp_df)
        
    if not df_full.empty:
        df_full.set_index('Data', inplace=True)
    return df_full

# ==============================================================================
# 4. EXECUÇÃO DO LOOP PRINCIPAL (MÊS A MÊS)
# ==============================================================================
datas_loop = pd.date_range(start=DATA_INICIO, end=DATA_FIM, freq='MS')
#dfs_list = []

print(f"\nIniciando a busca de dados de {DATA_INICIO.strftime('%Y-%m-%d')} até {DATA_FIM.strftime('%Y-%m-%d')}...")

for start_of_month in datas_loop:
    _, last_day_of_month = calendar.monthrange(start_of_month.year, start_of_month.month)
    end_of_month = date(start_of_month.year, start_of_month.month, last_day_of_month)
    
    # Garante que a data final do chunk não ultrapasse a DATA_FIM geral
    if end_of_month > DATA_FIM:
        end_of_month = DATA_FIM

    print(f"\nBuscando dados para o período: {start_of_month.strftime('%Y-%m-%d')} a {end_of_month.strftime('%Y-%m-%d')}")
    
    url = f"http://mananciais.sabesp.com.br/api/Mananciais/RepresasSistemasNivel/{start_of_month.strftime('%Y-%m-%d')}/{end_of_month.strftime('%Y-%m-%d')}/{SISTEMA_ID}"
    
    jsn = get_json(url)
    if jsn is None:
        print("  !!! Falha ao obter JSON. Pulando para o próximo mês.")
        continue

    df_base = json2df(jsn)

    # Extrai todas as tabelas de dados
    df_volumes = list_volumes(df_base)
    df_vazao = list_vazao(df_base)
    df_SE = list_SE(df_base)
    df_SC = list_SC(df_base)
    df_vazaoestruturas = list_vazaoestruturas(df_base)

    # Junta todas as tabelas do mês em uma só
    df_mes = pd.concat([df_volumes, df_vazao, df_SE, df_SC, df_vazaoestruturas], axis=1)
    dfs_list.append(df_mes)

    time.sleep(3) # Pausa para não sobrecarregar o servidor

# ==============================================================================
# 5. CONSOLIDAÇÃO FINAL E EXPORTAÇÃO
# ==============================================================================
if dfs_list:
    DATA_INICIO = date(2000, 1, 1)
    print("\nConsolidando todos os dados baixados...")
    df_final = pd.concat(dfs_list)
    
    # Remove linhas duplicadas (de sobreposição de meses, se houver) e ordena
    df_final = df_final[~df_final.index.duplicated(keep='last')]
    df_final.sort_index(inplace=True)

    # Garante que o DataFrame final cubra todo o período solicitado
    date_index = pd.date_range(start=DATA_INICIO, end=DATA_FIM, freq='D')
    df_final = df_final.reindex(date_index)

    # Exportação para CSV
    data_path = 'data'
    os.makedirs(data_path, exist_ok=True)
    filename = f"tab_Cantareira_{DATA_INICIO.strftime('%Y-%m-%d')}_ate_{DATA_FIM.strftime('%Y-%m-%d')}.csv"
    filepath = os.path.join(data_path, filename)
    
    df_final.to_csv(
        filepath,
        index=True,
        index_label='Data',
        header=True,
        sep=';',
        decimal=',',
        date_format='%d/%m/%Y',
        encoding='utf-8-sig'
    )
    
    print(f"\n✅ BRABA! Processo finalizado com sucesso!")
    print(f"Arquivo salvo em: {filepath}")
    print("\nVisualização das 5 primeiras linhas do resultado:")
    print(df_final.head())
    print("\nVisualização das 5 últimas linhas do resultado:")
    print(df_final.tail())
else:
    print("\n❌ Nenhuma informação foi baixada. Verifique os parâmetros e a conexão.")

In [62]:
dados2 = pd.read_csv('data/tab_Cantareira_2025-07-01_ate_2025-09-16.csv', sep=';', parse_dates=['Data'], dayfirst=True)
dados2 = pd.concat([dados2.filter(like='Cachoeira'),dados2['Data']], axis=1)
dados2

,Cachoeira_Nivel,Cachoeira_Volume,Cachoeira_Chuva,Cachoeira_ChuvaAcumuladaMensal,Cachoeira_QJusante,Cachoeira_VolumeMaximo,Cachoeira_VolumeMinimo,Cachoeira_VolumePorcentagem,Cachoeira_VolumeOperacional,Cachoeira_VolumeTotal,Cachoeira_VazaoNatural,Cachoeira_VazaoAfluente,Data
0,"816,33","73,85693325349818","0,0","0,0","4,5","116,57235880689602","46,92300215469965","38,67075360551688","26,93393109879853","73,85693325349818","0,686414125392737","25,28641412539274",2025-07-01
1,"816,33","73,85693325349818","0,2","0,2","4,54","116,57235880689602","46,92300215469965","38,67075360551688","26,93393109879853","73,85693325349818","0,28599999999999803","27,785999999999998",2025-07-02
2,"816,32","73,79077286822606","0,0","0,2","5,0","116,57235880689602","46,92300215469965","38,575762943072554","26,867770713526404","73,79077286822606","0,272254800091122","29,47225480009112",2025-07-03
3,"816,309","73,71804004027092","1,2","1,4","5,0","116,57235880689602","46,92300215469965","38,47133580770311","26,79503788557127","73,71804004027092","0,27418486163037203","27,374184861630376",2025-07-04
4,"816,32","73,79077286822606","0,0","1,4","5,0","116,57235880689602","46,92300215469965","38,575762943072554","26,867770713526404","73,79077286822606","1,058815138369624","33,058815138369624",2025-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,"817,17","79,55145803467276","0,0","0,0","5,5","116,57235880689602","46,92300215469965","46,84674410261647","32,62845587997311","79,55145803467276","0,213222689700892","31,61322268970089",2025-09-12
74,"817,21","79,82948919128741","0,4","0,4","5,5","116,57235880689602","46,92300215469965","47,245931072860905","32,906487036587755","79,82948919128741","0,557953201558394","29,757953201558394",2025-09-13
75,"817,23","79,96874201341723","0,0","0,4","5,5","116,57235880689602","46,92300215469965","47,44586518399017","33,045739858717575","79,96874201341723","0,10172247835438701","28,60172247835439",2025-09-14
76,"817,248","80,0942049213029","0,0","0,4","5,5","116,57235880689602","46,92300215469965","47,626000240387306","33,17120276660325","80,0942049213029","0,152116989417553","29,252116989417555",2025-09-15
77,"817,24","80,03842779022942","0,0","0,4","5,5","116,57235880689602","46,92300215469965","47,545917474724426","33,11542563552977","80,03842779022942","0,160431353316163","26,860431353316162",2025-09-16

In [64]:
dados = dados[(dados['Data da Medição'] >= '2025-07-01')&(dados['Data da Medição'] <= '2025-09-16')]

In [67]:
dados = dados.drop_duplicates().reset_index().drop('index', axis=1)

In [ ]:
df_final = pd.concat([dados, dados2], axis=1)

- Cota (m) -> Cachoeira_Nivel
- Volume Util (hm3) -> Cachoeira_VolumeOperacional
- Volume Útil (%) -> Cachoeira_VolumePorcentagem
- Afluencia (m³/s) -> Cachoeira_VazaoNatural
- defluencia (m³/s) -> Cachoeira_QJusante
- Data da Medição -> Data

In [69]:
pd.set_option('display.max_columns', None)
df_final

,Código do Reservatório,Reservatório,Cota (m),Volume Útil (hm³),Volume Útil (%),Afluência (m³/s),Defluência (m³/s),Data da Medição,Cachoeira_Nivel,Cachoeira_Volume,Cachoeira_Chuva,Cachoeira_ChuvaAcumuladaMensal,Cachoeira_QJusante,Cachoeira_VolumeMaximo,Cachoeira_VolumeMinimo,Cachoeira_VolumePorcentagem,Cachoeira_VolumeOperacional,Cachoeira_VolumeTotal,Cachoeira_VazaoNatural,Cachoeira_VazaoAfluente,Data
0,29002,CACHOEIRA,816.33,26.93,38.67,0.69,4.50,2025-07-01,"816,33","73,85693325349818","0,0","0,0","4,5","116,57235880689602","46,92300215469965","38,67075360551688","26,93393109879853","73,85693325349818","0,686414125392737","25,28641412539274",2025-07-01
1,29002,CACHOEIRA,816.33,26.93,38.67,0.29,4.54,2025-07-02,"816,33","73,85693325349818","0,2","0,2","4,54","116,57235880689602","46,92300215469965","38,67075360551688","26,93393109879853","73,85693325349818","0,28599999999999803","27,785999999999998",2025-07-02
2,29002,CACHOEIRA,816.32,26.87,38.58,0.27,5.00,2025-07-03,"816,32","73,79077286822606","0,0","0,2","5,0","116,57235880689602","46,92300215469965","38,575762943072554","26,867770713526404","73,79077286822606","0,272254800091122","29,47225480009112",2025-07-03
3,29002,CACHOEIRA,816.31,26.80,38.47,0.27,5.00,2025-07-04,"816,309","73,71804004027092","1,2","1,4","5,0","116,57235880689602","46,92300215469965","38,47133580770311","26,79503788557127","73,71804004027092","0,27418486163037203","27,374184861630376",2025-07-04
4,29002,CACHOEIRA,816.32,26.87,38.58,1.06,5.00,2025-07-05,"816,32","73,79077286822606","0,0","1,4","5,0","116,57235880689602","46,92300215469965","38,575762943072554","26,867770713526404","73,79077286822606","1,058815138369624","33,058815138369624",2025-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,29002,CACHOEIRA,817.17,32.63,46.85,0.21,5.50,2025-09-12,"817,17","79,55145803467276","0,0","0,0","5,5","116,57235880689602","46,92300215469965","46,84674410261647","32,62845587997311","79,55145803467276","0,213222689700892","31,61322268970089",2025-09-12
74,29002,CACHOEIRA,817.21,32.91,47.25,0.56,5.50,2025-09-13,"817,21","79,82948919128741","0,4","0,4","5,5","116,57235880689602","46,92300215469965","47,245931072860905","32,906487036587755","79,82948919128741","0,557953201558394","29,757953201558394",2025-09-13
75,29002,CACHOEIRA,817.23,33.05,47.45,0.10,5.50,2025-09-14,"817,23","79,96874201341723","0,0","0,4","5,5","116,57235880689602","46,92300215469965","47,44586518399017","33,045739858717575","79,96874201341723","0,10172247835438701","28,60172247835439",2025-09-14
76,29002,CACHOEIRA,817.25,33.17,47.63,0.15,5.50,2025-09-15,"817,248","80,0942049213029","0,0","0,4","5,5","116,57235880689602","46,92300215469965","47,626000240387306","33,17120276660325","80,0942049213029","0,152116989417553","29,252116989417555",2025-09-15
77,29002,CACHOEIRA,817.24,33.12,47.55,0.16,5.50,2025-09-16,"817,24","80,03842779022942","0,0","0,4","5,5","116,57235880689602","46,92300215469965","47,545917474724426","33,11542563552977","80,03842779022942","0,160431353316163","26,860431353316162",2025-09-16